from apps.data_media.models.video_data import *
from apps.data_media.models.news import *
from apps.data_media.models.photo_gallery_models import *
from apps.data_media.models.management import *
from apps.data_media.models.service import *
from apps.data_media.models.kodeks import *
from apps.data_media.models.visitors import *
from apps.data_media.models.organization import *
from apps.data_media.models.visitors import *