version: "3"
services:
  django:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/docker_demo/static
      - media_volume:/docker_demo/media
    command: >
      sh -c "python manage.py makemigrations faq moderator information contacts &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/docker_demo/static
      - media_volume:/docker_demo/media
    depends_on:
      - django
    networks:
      - app_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery:
    build: .
    container_name: celery
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
      - static_volume:/docker_demo/static
      - media_volume:/docker_demo/media
    depends_on:
      - django
      - redis
    networks:
      - app_network

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  app_network:
