version: '3.0'

name: 'archive-president'

services:
  web:
    build: .
    container_name: web
    command: sh -c "python manage.py makemigrations faq moderator information contacts && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    env_file:
      - .docker.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web

  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery
    command: celery -A config worker -l INFO
    depends_on:
      - web
      - redis

volumes:
  static_volume:
  media_volume:
  postgres_data: