version: '3.8'

services:
  django:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/docker_demo/static
      - media_volume:/docker_demo/media
    command: >
      sh -c "python manage.py makemigrations faq moderator information contacts &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: archive
      POSTGRES_USER: archive
      POSTGRES_PASSWORD: archive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/docker_demo/static
      - media_volume:/docker_demo/media
      - ./nginx/certbot/conf:/etc/letsencrypt  # Проверьте, что том для Certbot правильно монтируется здесь
    depends_on:
      - django
      - certbot  # Nginx зависит от Certbot для наличия SSL сертификатов
    networks:
      - app_network

  redis:
    image: redis
    container_name: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --nginx -d archive.pp.ua -d www.archive.pp.ua --email your-email@example.com --agree-tos --no-eff-email; sleep 12h & wait $${!}; done;'"
    networks:
      - app_network

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  app_network:
