from apps.data_media.views.video_data import *
from apps.data_media.views.news import *
from apps.data_media.views.photo_gallery_views import *
from apps.data_media.views.service import *
from apps.data_media.views.kodeks import *
from apps.data_media.views.search import *
from apps.data_media.views.quck_contacts_views import *
from apps.data_media.views.visitors import *
from apps.data_media.views.management import *
