from apps.information.serializers.video_data import *
from apps.information.serializers.news import *
from apps.information.serializers.photo_gallery_serializers import *
from apps.information.serializers.service import *
from apps.information.serializers.kodeks import *
from apps.information.serializers.organization import *
from apps.information.serializers.management import *
from apps.information.serializers.visitors import *
from apps.information.serializers.logo import *
