from apps.information.views.video_data import *
from apps.information.views.news import *
from apps.information.views.photo_gallery_views import *
from apps.information.views.service import *
from apps.information.views.kodeks import *
from apps.information.views.search import *
from apps.information.views.visitors import *
from apps.information.views.management import *
from apps.information.views.main import *
from apps.information.views.emblem import *
