from apps.information.models.video_data import *
from apps.information.models.news import *
from apps.information.models.photo_gallery_models import *
from apps.information.models.management import *
from apps.information.models.service import *
from apps.information.models.kodeks import *
from apps.information.models.visitors import *
from apps.information.models.organization import *
from apps.information.models.visitors import *
from apps.information.models.logo import *
from apps.information.models.about_archive import *
